version: "3.7"

services:
  app:
    build:      
      context: ./sgeg
      dockerfile: Dockerfile
    container_name: sgeg-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./sgeg:/var/www/html
      - uploads:/var/www/html/storage/app/public
    networks:
      - network-sgeg-db
      - network-sgeg-nginx
    depends_on:
      - db
    command: sh -c "php artisan migrate --force && php artisan db:seed --force && php-fpm" 
  db:
    image: mysql:8.0
    container_name: sgeg-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network-sgeg-db
  nginx:
    image: nginx:latest
    container_name: sgeg-nginx
    restart: unless-stopped
    ports:
      - 8000:80
      - 443:443
    volumes:
      - ./sgeg/public:/var/www/html/public
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - network-sgeg-nginx
  
networks:
  network-sgeg-db:
    driver: bridge
  network-sgeg-nginx:
    driver: bridge

volumes:
  db_data:
  uploads: